### ISSUE TITLE
Case: contractor/reviewer/client are contracts

### ISSUE THREAD

**Issue by SabaunT** [mixbytes/trust-deal#4]
It seems that there are some issues, when contractor/client/reviewer are contracts. It is ok if they have fallback functions, because `transfer` method is considered safe: it reverts if exception is met, it gives very few gas, so re-entrant call can't be performed.But we can really face problems if deals currency is ether and one of those actors is a contract without fallback function - deadlock.

Possible improvements:
- checking if address is a contract;
- change logic of reward transfer to "pull" over "push".

**Comment by Eenae** [comment]
Only `transfer` on the MVP stage, no pulls.
