### ISSUE TITLE
More event based deal

### ISSUE THREAD

**Issue by SabaunT** [mixbytes/trust-deal#5]
I suggest deelply using event based development.
One great feature is that although we do not save some data into contract storage, we still retrieve data from blockchain (from contract state) using events. Consequently, we do not "save" anything on front-end.

More specifically:
 - minutes delivered and logTimestamp (ITERATION state) could be emitted (`ApplicationAdded` event) and retrieved from the contract events. This data is view only for front-end, so we can remove it from contract storage.
 - `getState`, `getReviewer`, `getClient`, `getContractor` and other view functions could be replaced with event handling. For example: for each contract we have a number of events that signals current contract state. So on front-end this task ends-up in getting last state signaling event. Just for now we have `DealInitialized`, `ReviewerProposed`, `ReviewerAcceptedConditions` and `ReviewerDeclinedConditions`, `ContractorChosen`, `LoggedWork`, `IterationFinished`, `DealTaskReviewedPositively`, `DealEndedUp(currentState)`. So, we can use them as state flags. These events also contain information, related to deal current state: client/contractor/reviewer addresses, minutes logged, iteration stats and e.t.c.

**Comment by Eenae** [comment]
“Premature optimization is the root of all evil” 
-- Donald Knuth
